;['PROGRAM OF DEBIT CARD']


;MACRO FOR PRINTING STRINGS
PRINT MACRO P1 
MOV DX,OFFSET P1
MOV AH,9
INT 21H
ENDM


DOSSEG
.MODEL SMALL
.STACK 100H 
.DATA
CURRENTBAL DW 12    ;INITIALIZING CURRENT BALANCE IN 16 BIT
PIN1 DB '2$'
PIN2 DB '7$'
PIN3 DB '1$'
STR1 DB 10,13,'ENTERPIN:',10,13,10,13,'$'
STR2 DB 10,13,'                       INVALID PIN$'
STR3 DB 10,13,'                        VALID PIN$'
STR4 DB 10,13,10,13,'ENTER CHOICE:',10,13,'$'
STR5 DB 10,13,'1.  ADD MONEY$'
STR6 DB 10,13,'2.  PURCHASE ITEMS     [2 DOLLAR DISCOUNT APPLIED ON PURCHASE GREATER THAN 6]$'
STR7 DB 10,13,'3.  SHOW CURRENT BALANCE',10,13,10,13,'$'
STR8 DB 10,13,'                    ENTER AMOUNT:',10,13,10,13,'$'
STR9 DB 10,13,'                    ENTER TOTAL BILL:',10,13,10,13,'$'
STR10 DB 10,13,10,13,'PRICE AFTER DISCOUNT:',10,13,'$'
STR11 DB 10,13,10,13,'CURRENT BALANCE IS: $'
STR12 DB 10,13,10,13,'MONEY ADDED SUCCESSFULLY!',10,13,'$'
STR13 DB 10,13,10,13,'AMOUNT DEBITED SUCCESSFULLY!',10,13,'$'
STR14 DB 10,13,10,13,'                   CHECKING BALANCE........',10,13,'$'
STR15 DB 10,13,10,13,'SUFFICIENT BALANCE ',10,13,'$'
STR16 DB 10,13,10,13,'TRANSACTION CANNOT BE COMPLETED;',10,13,10,13,'                INSUFFICIENT BALANCE',10,13,'           PLEASE ADD MONEY IN ACCOUNT MORE THAN 10',10,13,'$'
STR17 DB 10,13,10,13,'PERFORM OTHER OPERATION PRESS 1 TO GO TO CHOICE OR 0 TO EXIT',10,13,10,13,'$'


.CODE
MAIN PROC

    ;FOR INITIALIZING VARIABLES IN .DATA TO THE HEAP MEMORY
    MOV AX,@DATA 
    MOV DS,AX
    
    ;ENTER PIN
    PRINT STR1
    ;CALL CHECKPIN PROCEDURE FOR CHECKING PIN
    CALL CHECKPIN

    ;ENTER THE CHOICE TO PERFORM OPERATION 
    CHOICES:
    PRINT STR4
    PRINT STR5                     
    PRINT STR6
    PRINT STR7  

    ;INPUT NUMBER OF YOUR CHOICE
    MOV AH,1
    INT 21H

    MOV BL,1

    ;TO CONVERT INPUT FROM ASCII TO A NUMBER
    SUB AL,48

    ;IF 1 THEN JUMP TO CHOICE 1
    CMP BL,AL
    JE CHOICE1 

    MOV BL,2

    ;IF 2 THEN JUMP TO CHOICE 2
    CMP BL,AL               
    JE CHOICE2

    MOV BL,3

    ;IF 3 THEN JUMP TO CHOICE 3
    CMP BL,AL
    JE ADJUST1

    ;TO EXIT IF CHOICE IS WRONG
    MOV AH,4CH  
    INT 21H 
    
    ;JUMP TO CHOICE3
    ADJUST1:
    JMP CHOICE3   


    ;WHEN BALANCE IS NOT SUFFICIENT      
    INSUFBAL:
    PRINT STR16
    ;TO PRINT UPDATED BALANCE
    JMP CHOICE3
    

    ;FOR ADDING MONEY
    CHOICE1:
    PRINT STR8

    ;INPUT MONEY TO ADD INTO THE ACCOUNT
    MOV AH,1
    INT 21H 
    SUB AL,48                  
    MOV CX,CURRENTBAL
    ADD CX,AX
    MOV CURRENTBAL,CX
    PRINT STR12
    
    ;TO PRINT UPDATED BALANCE JUMP TO CHOICE3
    JMP CHOICE3           
   
    
    ;FOR PURCHASE ITEMS
    CHOICE2:
    PRINT STR14

    ;TO HOLD CURRENT BALANCE TO CX FOR COMPARING
    MOV CX,CURRENTBAL

    ;TO PRINT CURRENT BALANCE
    MOV AX,CURRENTBAL
    AAM
    MOV CH,AH
    MOV CL,AL          
    MOV DL,CH
    ADD DL,48
    MOV AH,2
    INT 21H   
    MOV DL,CL
    ADD DL,48
    INT 21H
    
    ;TO CHECK BALANCE IS SUFFICIENT OR NOT IF IT IS THEN CONTINUE IF NOT THEN IT JUMPS TO INSUFF BALANCE
    CMP CX,10
    JL INSUFBAL 
    
    PRINT STR15      
    PRINT STR9

    ;INPUT AMOUNT YOU WANT TO PURCHASE
    MOV AH,1
    INT 21H          
    SUB AL,48

    ;IF AMOUNT IS GREATER THAN 6 IT JUMPS TO APPLYDIS 
    CMP AL,6
    JG APPLYDIS
    
    ;TO DEDUCT PURCHASE AMOUNT FROM CURRENT BALANCE WHEN BALANCE IS SUFFICIENT
    SUFBAL:
    MOV CX,CURRENTBAL
    SUB CX,AX       
    MOV CURRENTBAL,CX
    PRINT STR13

    ;TO PRINT UPDATED BALANCE
    JMP CHOICE3
    
    ;APPLYING 2$ DISCOUNT FOR PURCHASE AMOUNT GREATER THAN 6
    APPLYDIS:
    MOV CL,AL
    PRINT STR10
    MOV AL,CL
    SUB AL,2
    MOV DL,AL          
    ADD DL,48

    ;TO PRINT DISCOUNTED PRICE
    MOV AH,2
    INT 21H
    MOV AL,DL
    SUB AL,48 
    
    ;JUMP TO SUFFICIENT BALANCE TO DEDUCT PURCHASE AMOUNT AFTER DISCOUNT
    JMP SUFBAL 
    

    ;FOR SHOWING CURRENT BALANCE
    CHOICE3:
    PRINT STR11
    MOV AX,CURRENTBAL
    AAM
    MOV CH,AH
    MOV CL,AL          
    MOV DL,CH
    ADD DL,48
    MOV AH,2
    INT 21H   
    MOV DL,CL
    ADD DL,48
    INT 21H
    
    ;INPUT 1 TO PERFORM MORE OPERATIONS OR 0 TO EXIT
    PRINT STR17
    MOV AH,1
    INT 21H   
    SUB AL,48 

    ;JUMP TO ADJUST2 IF INPUT IS 1
    CMP AL,1
    JE ADJUST2

    ;EXIT IF INPUT IS 0
    CMP AL,0
    JE EXIT

    
    ;JUMP TO CHOICES
    ADJUST2:
    JMP CHOICES


;PROCEDURE FOR CHECKING PIN IF VALID OR NOT
CHECKPIN PROC
    MOV AH,1
    INT 21H
    MOV BL,PIN1

    ;JUMP TO PASS1 IF 1st PIN IS CORRECT
    CMP BL,AL
    JE PASS1

    ;OTHERWISE JUMP TO INVALID
    JMP INVALID
    PASS1:
    MOV AH,1
    INT 21H
    MOV BL,PIN2

    ;JUMP TO PASS2 IF 2nd PIN IS CORRECT
    CMP BL,AL
    JE PASS2  

    ;OTHERWISE JUMP TO INVALID
    JMP INVALID        
    PASS2:
    MOV AH,1
    INT 21H
    MOV BL,PIN3

    ;JUMP TO PASS3 IF 3rd PIN IS CORRECT
    CMP BL,AL
    JE PASS3  

    ;OTHERWISE JUMP TO INVALID 
    JMP INVALID

    CHECKPIN ENDP

    ;WHEN PIN IS WRONG
    INVALID:
    PRINT STR2
    MOV AH,4CH 
    INT 21H
    
    ;WHEN PIN IS CORRECT
    PASS3:
    PRINT STR3
    JMP CHOICES

    ;TO EXIT FROM REGISTER MODE
    EXIT: 
    MOV AH,4CH
    INT 21H


    MAIN ENDP  
    END MAIN